version: "3.8"

services:
  nestapp:
    image: nameco131211/nest-first:latest
    ports:
      - "3001:3000"
    env_file:
      - .env.development
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Añade esta línea
    env_file:
      - .env.development

volumes:
  pgdata:
